# food-delivery/docker-compose.yml
version: "3.8"

services:
  php:
    build: .
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
      - pgbouncer 
      
  # New Apache service
  apache:
    image: httpd:2.4
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./apache.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - php
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # ✅ Add PgBouncer service
  pgbouncer:
    image: edoburu/pgbouncer
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: food_delivery       #database name
      DB_USER: food_user
      DB_PASSWORD: secure_password
      POOL_MODE: transaction
      MAX_CLIENT_CONN: 500
      DEFAULT_POOL_SIZE: 20
      LISTEN_PORT: 6432
    ports:
      - "6432:6432"
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: food_user
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: food_delivery
    ports:
      - "5432:5432"  # Keep for direct access if needed
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
